### PR TITLE
Don't reposition elements too much

### PR DESCRIPTION
**Pull request by kinging123**
Repositioning only when needed.

### CODE REVIEW

**Comment by travisneilson** [comment]
Can you tell me how this works? Instead of using `Math.min` you are using  an `if(offset > 0)`

I get what is happening functionally, but why is it better?

**Comment by travisneilson** [comment]
Oh, also; I'm going to make a video where I explain these pull requests (giving credit to you guys, of course) and pull them in.

I'll be pulling on Tuesday (26th) I'll be sure to get this on the video so everyone can see the awesome work you did!

Thanks for everything!

**Comment by reuvenkarasik** [comment]
Hey, with your way, every time the user scrolls the element gets repositioned. Sometimes the new position is different than the old position (and in those cases the element moves) but in some cases the offset is less than 0 and the new position is equal to the old position, but the element is still being repositioned.

In my code, the repositioning only happends if the new position **is** different than the old one, meaning only if there's a point to move the element.
This means the computer thinks only when it's needed, and you use less resources, which is always a good thing in heavy websites like "Black Bird"'s.
I hope this explanation is good enough, but please tell me if you're still not sure why it's better ;)

I beleive no changes are needed in order to merge this pull request (there's a notice bellow saying _"This pull request can be automatically merged by project collaborators."_)

**Comment by travisneilson** [comment]
Oh, that makes sense now! cool :)

**Pull request merged**
