### PR TITLE
Just hacking stuff

### PR DESCRIPTION
**Pull request by ajspeller**
Just wanted to try to fork and create a pull request for a simple change.  I added a conditional statement that applies the parallax transitions when the objects in the parallax container are visible.

### CODE REVIEW

**Comment by systimotic** [comment]
This sounds really cool! If I think that this makes sure it's only parallax whenever you can see it, thus increasing performance, am I right?

**Comment by ajspeller** [comment]
Thanks.  Yes sir, that is exactly the point.

**Comment by travisneilson** [comment]
Hey this is great stuff, thank you so much! I'm going to make a video where I explain these pull requests (giving credit to you guys, of course) and pull them in.

If you can resolve this Merge Conflict before next Tuesday (26th) I'll be sure to get this on the video so everyone can see the awesome work you did!

**Comment by travisneilson** [comment]
I copied your work into a new branch and pulled it in. Thanks for your help!!

**Pull request closed without merging**
