### PR TITLE
Master

### PR DESCRIPTION
**Pull request by rasmushjulskov**
Performance optimized the animation with 3 techniques:
1) don’t animation stuff out off view.
2) Round values — especially in px.
3) Request an animation in the next repaint.

### CODE REVIEW

**Comment by travisneilson** [comment]
Hey this is great stuff, thank you so much! I'm going to make a video where I explain these pull requests (giving credit to you guys, of course) and pull them in.

If you can resolve this Merge Conflict before next Tuesday (26th) I'll be sure to get this on the video so everyone can see the awesome work you did!

**Comment by rasmushjulskov** [comment]
You can't just rebase the branch? You should delete the 02597d4 changes, if you don't need the relative paths.

**Comment by rasmushjulskov** [comment]
Sorry i'm responding this late. Hope you still find the time :) I can't commit compressed code anymore, as my CodeKit trial expired.

I've merged the function.js file : https://gist.github.com/Rhjulskov/3ceb229f29090cf2c3b8 Just compile that aswell as the index.jade file, and the merge should be resolved :)

**Comment by travisneilson** [comment]
I've moved some of your work here into another branch and pulled that in, giving you full credit. Thank you so much for your PR :)

**Pull request closed without merging**
